spring.application.name=TaraTulong


#Database connection //local set up

spring.datasource.url=jdbc:postgresql://localhost:5432/taratulong_db
spring.datasource.username=postgres
spring.datasource.password=pass

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
application.security.jwt.secret-key=${JWT_SECRET}

#-------------------------------------------------#


## 1. Turn on SQL printing and make it readable
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
## 2. Highlight SQL comments (Useful if you add custom comments to your @Query)
#spring.jpa.properties.hibernate.use_sql_comments=true
#
## 3. Show the actual data inside the '?' parameters (For Spring Boot 3 / Hibernate 6)
#logging.level.org.hibernate.orm.jdbc.bind=TRACE
#
## 4. Turn on the Hibernate Statistics Engine (Execution times and query counts)
#spring.jpa.properties.hibernate.generate_statistics=true
#logging.level.org.hibernate.stat=DEBUG