CREATE TABLE admin
(
    id   BIGINT       NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT pk_admin PRIMARY KEY (id)
);

CREATE TABLE app_users
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid      UUID                                    NOT NULL,
    email     VARCHAR(255)                            NOT NULL,
    password  VARCHAR(255)                            NOT NULL,
    role      VARCHAR(255)                            NOT NULL,
    join_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    deleted   BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_app_users PRIMARY KEY (id)
);

CREATE TABLE event
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organizer_id    BIGINT,
    version         INTEGER                                 NOT NULL,
    title           VARCHAR(255)                            NOT NULL,
    description     TEXT                                    NOT NULL,
    start_date_time TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_date_time   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    cut_off_time    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    location        VARCHAR(255)                            NOT NULL,
    slots_available INTEGER                                 NOT NULL,
    deleted         BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_event PRIMARY KEY (id)
);

CREATE TABLE org
(
    id          BIGINT       NOT NULL,
    name        VARCHAR(255) NOT NULL,
    description TEXT,
    location    VARCHAR(255) NOT NULL,
    status      VARCHAR(255) NOT NULL,
    approved_by BIGINT,
    CONSTRAINT pk_org PRIMARY KEY (id)
);

CREATE TABLE registration
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    volunteer_id        BIGINT,
    event_id            BIGINT,
    registration_status VARCHAR(255)                            NOT NULL,
    attendance_status   VARCHAR(255),
    rating              INTEGER,
    feedback            TEXT,
    applied_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_registration PRIMARY KEY (id)
);

CREATE TABLE volunteer
(
    id                           BIGINT        NOT NULL,
    first_name                   VARCHAR(50)   NOT NULL,
    last_name                    VARCHAR(50)   NOT NULL,
    attendance_rate              DECIMAL(5, 2) NOT NULL,
    total_events_attended        INTEGER       NOT NULL,
    total_approved_registrations INTEGER       NOT NULL,
    trust_score                  INTEGER       NOT NULL,
    CONSTRAINT pk_volunteer PRIMARY KEY (id)
);

ALTER TABLE app_users
    ADD CONSTRAINT uc_app_users_email UNIQUE (email);

ALTER TABLE app_users
    ADD CONSTRAINT uc_app_users_uuid UNIQUE (uuid);

ALTER TABLE admin
    ADD CONSTRAINT FK_ADMIN_ON_ID FOREIGN KEY (id) REFERENCES app_users (id);

ALTER TABLE event
    ADD CONSTRAINT FK_EVENT_ON_ORGANIZER FOREIGN KEY (organizer_id) REFERENCES org (id);

ALTER TABLE org
    ADD CONSTRAINT FK_ORG_ON_APPROVED_BY FOREIGN KEY (approved_by) REFERENCES admin (id);

ALTER TABLE org
    ADD CONSTRAINT FK_ORG_ON_ID FOREIGN KEY (id) REFERENCES app_users (id);

ALTER TABLE registration
    ADD CONSTRAINT FK_REGISTRATION_ON_EVENT FOREIGN KEY (event_id) REFERENCES event (id);

CREATE INDEX idx_registration_event ON registration (event_id);

ALTER TABLE registration
    ADD CONSTRAINT FK_REGISTRATION_ON_VOLUNTEER FOREIGN KEY (volunteer_id) REFERENCES volunteer (id);

CREATE INDEX idx_registration_volunteer ON registration (volunteer_id);

ALTER TABLE volunteer
    ADD CONSTRAINT FK_VOLUNTEER_ON_ID FOREIGN KEY (id) REFERENCES app_users (id);