-- Category table for user-defined tags (hashtag-style)
CREATE TABLE category
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(100) NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id)
);

ALTER TABLE category
    ADD CONSTRAINT uc_category_name UNIQUE (name);

CREATE INDEX idx_category_name ON category (name);

-- Join table for Event <-> Category (ManyToMany)
CREATE TABLE event_category
(
    event_id    BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    CONSTRAINT pk_event_category PRIMARY KEY (event_id, category_id),
    CONSTRAINT fk_event_category_event FOREIGN KEY (event_id) REFERENCES event (id),
    CONSTRAINT fk_event_category_category FOREIGN KEY (category_id) REFERENCES category (id)
);

CREATE INDEX idx_event_category_event ON event_category (event_id);
CREATE INDEX idx_event_category_category ON event_category (category_id);
